name: Code Quality

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  lint:
    name: Code Quality Check
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install development dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r tools/requirements-dev.txt

    - name: Check dependencies
      run: |
        cd tools/
        make check-deps

    - name: Run linters
      run: |
        cd tools/
        make lint

    - name: Check if auto-fix would make changes
      run: |
        cd tools/
        # Run fix in dry-run mode to see what would change
        python3 lint-and-fix.py --fix
        # Check if there are any changes
        if [ -n "$(git status --porcelain)" ]; then
          echo "❌ Code formatting issues found. Run 'cd tools && make fix' to fix them."
          git diff --color=always
          exit 1
        else
          echo "✅ Code formatting is correct."
        fi